add more sophisticated health check for deplyo script

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -36,6 +36,17 @@ jobs:
 
             docker image prune -f
 
-            curl --fail --retry 10 --retry-delay 2 --retry-connrefused --max-time 5  http://localhost:4001
+            for i in {1..20}; do
+              if curl --fail --silent --show-error http://localhost:4001; then
+                echo "Application is healthy."
+                exit 0
+              fi
+
+              echo "Waiting for application to become healthy ($i/20)..."
+              sleep 5
+            done
+
+            echo "Health check failed."
+            exit 1
 
 
